# Generated by Django 2.0.2 on 2018-02-01 20:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=200, unique=True)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('province', models.CharField(blank=True, max_length=200)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('ip_address',),
            },
        ),
    ]
